"""initial

Revision ID: 620153641067
Revises: 
Create Date: 2024-01-26 00:25:14.497439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '620153641067'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'Books',
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=30), nullable=True),
        sa.Column('author', sa.String(length=30), nullable=True),
        sa.Column('published_date', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('book_id')
    )

    op.create_table(
        'Genres',
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.Column('genre_name', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('genre_id')
    )

    op.create_table(
        'BookGenres',
        sa.Column('book_id', sa.Integer(), nullable=False),
        sa.Column('genre_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['Books.book_id'], ),
        sa.ForeignKeyConstraint(['genre_id'], ['Genres.genre_id'], ),
        sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookGenres')
    op.drop_table('Genres')
    op.drop_table('Books')
    # ### end Alembic commands ###
