"""initial

Revision ID: e1f77ba5819b
Revises: 620153641067
Create Date: 2024-01-26 00:42:39.177296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e1f77ba5819b'
down_revision: Union[str, None] = '620153641067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'BookFiles',
        sa.Column('file_id', sa.Integer(), nullable=False),
        sa.Column('book_id', sa.Integer(), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('file_format', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['book_id'], ['Books.book_id'], ),
        sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BookFiles')
    # ### end Alembic commands ###
