apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: bws-container
        image: book_web_service-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "db-service"
        - name: S3_HOST
          value: "minio-service"
#      initContainers:
#        - name: bws-migrate-container
#          image: book_web_service-app
#          imagePullPolicy: IfNotPresent
#          args: [ "migrate" ]
#          env:
#          - name: DB_HOST
#            value: "db-service"